// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::user;
use diesel::{Insertable, Queryable};

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub login: String,
    pub email: String,
    pub password: String,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
}

impl User {
    pub fn new() -> User {
        User {
            id: 0,
            login: "no user".to_string(),
            email: "no email".to_string(),
            password: "no password".to_string(),
            first_name: Some("no name".to_string()),
            last_name: Some("no last name".to_string())
        }
    }
}

#[derive(Insertable)]
#[diesel(table_name = user)]
pub struct NewUser<'a> {
    pub login: &'a str,
    pub email: &'a str,
    pub password: &'a str,
}
